### ISSUE TITLE
Build phlow-init command

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#1]
Create the phlow init command
 - git wrapping
 - configuration
   - default branch

**Comment by lakruzz** [comment]
We'll split up in more individual features

**Comment by JKrag** [comment]
If we are splitting it up, then this is not a "won't have"! I assume we are splitting it up into more workable chunks because we *do want* it.

I suggest that we handle these by leaving them in "needs grooming" with a comment about split up work in progress, and then close the issue when we are ready to reference with 
> *Will be implemented by issues #xx #yy #zz*
