### ISSUE TITLE
The phlow seems to be broken

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#197]
Somehow `master` seems to be hardcoded!

![image](https://user-images.githubusercontent.com/155492/29493593-a102252a-8599-11e7-9466-28f4f58a64c7.png)

....the integration branch for this repo is `gh-pages`

**Comment by groenborg** [comment]
@lakruzz Well this is totally expected behavior! From our requirements we wanted phlow to work with a config file, and return to a default behaviour! Which is origin/master if no phlow files are specified.. Hence the break in backwards compatibility. I refer to the documentation located here https://github.com/Praqma/git-phlow/tree/master/docs

**Comment by groenborg** [comment]
Create the .phlow INI config file with the right configuration and try again! If that does not work there is a bug!
