### ISSUE TITLE
Jira/Bitbucket Smart Commit expect hashtag in front of magic word

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#257]
I just learned that the Smart Commit feature we rely on uses hashtag for commands.

So `close` should be `#close` and for say issues `PRJ-17` our close message have to be `PRJ-17 #close`.

This is slightly different from Github.

**Comment by groenborg** [comment]
We can try to auto detect the service the user is using, however it would be easier to use the configuration, since that can tell us directly what service you use.

So now wrap-up will work like this:

`git phlow wrapup` > using default conf or internal default

`git phlow wrapup -t jira` > using jira conf in .gitconfig
