### ISSUE TITLE
Don't rebase that integration branch during deliver --local

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#268]
Maybe related to #264 (not sure though)

![image](https://user-images.githubusercontent.com/155492/31859243-8bc6f5cc-b709-11e7-8594-421fae6a5b45.png)

I'm not to fond of this part:

```shell
Exec: git checkout gh-pages
Exec: git pull --rebase
Exec: git merge 318-review-af-context-kapitlet
```

Don't do `git pull --rebase` (in context of the integration branch) - the goal should be to synchronise with the remote, so the `--rebase` part is relevant in context of `318-review-af-context-kapitlet` but it's 100% off in context of the integration branch, since it's potentially altering the commits on the branch. I might lead to a merge conflict.

Consequently a `deliver --local` could have the highly unintended side effect - that I end up with a merge conflict on my local `gh-pages` branch.

Ouuuuch - that's gotta hurt!

**Comment by buep** [comment]
The conclusion of what we want on this matter is that **we expect a git phlow deliver --local to take the commit(s) and rebase them on top of newest integration branch.**

If I assume I'm still on the feature branch and the above other examples, one way to do it would be to do:

```
git fetch #to make sure gh-pages are in sync with remote gh-pages branch
git rebase --onto gh-pages # rebasing on top of latest integration branch to avoid rejected merges in all the almost trivial cases
git checkout gh-pages
git merge 318-review-af-context-kapitlet
```

But is a good idea to checkout `gh-pages` locally? Could I do without a local version of the integration branch if I liked that?
@JKrag how would you do the rebase to integration branch when doing a local deliver?

**Comment by groenborg** [comment]
@buep I have worked through this together with @JKrag. We arrived at the following writeup:

# local deliver conclusion
There are three specific scenarious I think are important to git phlow, and will make this discussion easier. (these scenarios should probably be included in documentation at some point).

1. Normal behaviour, we have a pretested integration server and we only care for pushing branches prefixed with `ready/` or the like. (i.e. normal `deliver`)) 
In this scenario our already implemented logic should suffice. There only real headache here is that fixing a failing build requires a few extra steps. 

2. Currently no CI service, but still connected to a remote on github. This could be projects without a build server, or times where the build server/pipeline is down and I still need to work.  In both cases, `deliver --local <test>` is our way of providing a way for them 
to do pretested integration locally and push the changes if the test succeeds. 

3. Offline. Either temporarily no internet and thus no CI service or git remote available, or when working on a purely local/personal repo. This scenario is not supported and we need to figure out what we want to do. But ideally an implementation where we can have our issues locally as JSON and interpreted by the tool, would enable us to e.g. store our work if we know we are traveling. 

The important thing is to notice the differece between case 2 and case 3, as this enables a much cleaner discussion about what behaviour we want for case 2. 

### Solution to scenario 2
We are always working with our remote, so right now it does not make sense to `pull --rebase` on master, because we only want that to track the history of our origin and not do actual work on it.
So a potential workflow instead would be to alter the existing one to only work with the remote. So it would look like this: 

`git deliver --local <test_script>` should do the follwoing:

```
# on feat branch
git fetch
git rebase --onto origin/master

# execute <test_script>

# If test succeeds:
git push origin <feature_branch>:master
git fetch origin/master
``` 

Even if the tests fail, we still want the rebase because we still want our work to be replayed on top of the latest changes no matter what. 


We can even add `--squash` to the rebase and make it an optional flag for users who want more control over their work. The default workflow should however be without the squash. This will be suggested as a separate feature as soon as @JKrag and I have fleshed it out.

**Comment by buep** [comment]
I read that as you agree we just remove the `--rebase` from the pull and deliver as one commit with rebase if it is a local deliver.

Thanks for the input. The write-up should be part of of our more formal work with The Phlow.
