### ISSUE TITLE
Cleanup command fails for multiple delivered branches

### ISSUE THREAD

**Issue by mortench3000** [Praqma/git-phlow#290]
```git phlow cleanup``` failed for the 2nd delivered branch with no reason/explanation
Running the same command again successfully deletes the branch

```
[praqma.com]$ git branch
  delivered/1136-update-persona-for-mortench3000
  delivered/1227-fix-bad-image-filename
* gh-pages
[praqma.com]$ git phlow cleanup
Deleted local branch delivered/1136-update-persona-for-mortench3000 
Could not delete branch delivered/1227-fix-bad-image-filename 
[praqma.com]$ git phlow cleanup
Deleted local branch delivered/1227-fix-bad-image-filename
```

**Comment by groenborg** [comment]
@mortench3000 The command only deletes branches with `git branch  -d` which means unmerged changes are not deleted. Sometimes if the branch was delivered using a rebase a new sha will be created and git cannot see if the commit of the branch has ended up on master. For this case I believe that it is because we do a fetch at the end of the command, to prune untracked branches, and therefore updates what branches have been integrated. The second run will then register that the merges was changed, and delete the branch. I will say this is expected behaviour.

**Comment by mortench3000** [comment]
Ok - If the command fails, just run it again.
Thanks for the technical explanation though...

**Comment by groenborg** [comment]
However it could be a little more clear
