### ISSUE TITLE
Missing network connection should be handled and reported gracefully

### ISSUE THREAD

**Issue by MichaelMadsen** [Praqma/git-phlow#30]

**Comment by JKrag** [comment]
@lakruzz Please don't close issues without a comment about why we "won't have" a certain feature. If for no other reason then because this project *is* already being run in an open community and it is very discouraging to new people to see issues being closed without comment.

It might have been discussed at some meeting, and obvious for the participants, but it leaves no comments for the person who reported the bug and no information for people that run into similar problems later and find this bug before reporting their own.

Is the real problem here that the bug is not descriptive enough? Then we should ask @MichaelMadsen if he can provide more details.

**Comment by lakruzz** [comment]
@JKrag @MichaelMadsen 

Right - sorry

I realized that this is brutal, I'd try to be more descriptive -I _am_ actually very much in favor of that myself. So apologies for that.

Git itself will continue to work, but the connection to HitHub obviously requires a network connection - on the other hand, this is not in anyway special for the phlow - it's a feature of _all_ GitHub related commands, so I don't se a need for us to make special considerations.

But I agree with Jan:

If we're talking about specific cases with bad, poor or missing error messages, let's get them up her individually.
